In [48]:
# #'author'= ' Sayak Ghosh'
# #'date' = '28Aug 2022'
# #import pkgs

# import pandas as pd
# import numpy as np

# import matplotlib.pyplot as plt
# import seaborn as sns

# #!pip install neattext
# import neattext.functions as nfx

# import itertools #itertools is a collection of tools is used to handeling the iterator( like list) 
# from sklearn.model_selection import train_test_split
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.linear_model import PassiveAggressiveClassifier
# from sklearn.ensemble import RandomForestClassifier

# from sklearn.metrics import accuracy_score, confusion_matrix


# -*- coding: utf-8 -*-
"""
use voting calssifier
in hand soft voting and hard voting 
Created on Wed Aug  4 01:56:17 2021

@author: Sayak Ghosh
"""


import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, AdaBoostClassifier, VotingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn import metrics
from sklearn.neural_network import MLPClassifier

In [49]:
#import dataset

df=pd.read_csv("Constraint_Train.csv")

In [50]:
df.head()

id                                              tweet label
0   1  The CDC currently reports 99031 deaths. In gen...  real
1   2  States reported 1121 deaths a small rise from ...  real
2   3  Politically Correct Woman (Almost) Uses Pandem...  fake
3   4  #IndiaFightsCorona: We have 1524 #COVID testin...  real
4   5  Populous states can generate large case counts...  real

In [51]:
df.shape

(6420, 3)

In [52]:
df.unique

AttributeError: 'DataFrame' object has no attribute 'unique'

In [53]:
x=df['tweet']
y=df['label']

In [54]:
x.head()

0    The CDC currently reports 99031 deaths. In gen...
1    States reported 1121 deaths a small rise from ...
2    Politically Correct Woman (Almost) Uses Pandem...
3    #IndiaFightsCorona: We have 1524 #COVID testin...
4    Populous states can generate large case counts...
Name: tweet, dtype: object

In [55]:
y.head()

0    real
1    real
2    fake
3    real
4    real
Name: label, dtype: object

In [56]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state=7)

In [57]:
#preprocessing of the data 


from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words = 'english',max_df = 0.7)

tfidf_train = tfidf_vectorizer.fit_transform(x_train)

tfidf_test = tfidf_vectorizer.transform(x_test)

In [58]:
x_test

4463    Our daily update is published. We’ve now track...
1182    RT @CDC_eHealth: CDC leads a new national geno...
2015    _Indian Prime Minister Narendra Modi has been ...
5424    NEWS! Coronavirus ‘a serious and imminent thre...
6010    Man Could Soon Be Eating Rice For Breakfast, D...
                              ...                        
5605    RT @PIB_India: #IndiaFightsCOVID19 ✅More than ...
6258    We're getting a lot of questions about Georgia...
5423    Prepare for the possible spread of #COVID19 in...
361     #Coronavirus surges in Arizona. https://t.co/z...
4117    A COVID-19 case has been diagnosed in Yedikule...
Name: tweet, Length: 1284, dtype: object

# PassiveAggressiveClassifier

In [59]:
#clasifier or algorithm to learn th emodel 

passive = PassiveAggressiveClassifier(max_iter = 50)
passive.fit(tfidf_train,y_train)
y_pred1 = passive.predict(tfidf_test)


In [60]:
print(y_pred1)

['real' 'real' 'fake' ... 'real' 'real' 'fake']


In [61]:
score = accuracy_score(y_test,y_pred1)
print(score)

0.9548286604361371


In [62]:
confusion_matrix(y_test,y_pred1)

array([[570,  37],
       [ 21, 656]], dtype=int64)

# RandomForestClassifier

In [63]:
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(tfidf_train, y_train) 

RandomForestClassifier(n_estimators=1000, random_state=0)

In [64]:
y_pred2 = classifier.predict(tfidf_test)

In [65]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))
print(accuracy_score(y_test, y_pred2))

[[573  34]
 [ 56 621]]
              precision    recall  f1-score   support

        fake       0.91      0.94      0.93       607
        real       0.95      0.92      0.93       677

    accuracy                           0.93      1284
   macro avg       0.93      0.93      0.93      1284
weighted avg       0.93      0.93      0.93      1284

0.9299065420560748


# Multinomial NB 

In [66]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB().fit(tfidf_train,y_train)

In [67]:
y_pred3 = clf.predict(tfidf_test)

In [68]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))
print(accuracy_score(y_test, y_pred3))

[[525  82]
 [ 20 657]]
              precision    recall  f1-score   support

        fake       0.96      0.86      0.91       607
        real       0.89      0.97      0.93       677

    accuracy                           0.92      1284
   macro avg       0.93      0.92      0.92      1284
weighted avg       0.92      0.92      0.92      1284

0.9205607476635514


In [69]:
from sklearn import model_selection, svm

SVM = svm.SVC(C=1.0, kernel='linear', degree=3, gamma='auto')
SVM.fit(tfidf_train,y_train)


SVC(gamma='auto', kernel='linear')

In [70]:
y_pred4 = SVM.predict(tfidf_test)
#print("Accuracy: ",accuracy_score(predictions_SVM, Test_Y)*100)

In [71]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred4))
print(classification_report(y_test,y_pred4))
print(accuracy_score(y_test, y_pred4))

[[568  39]
 [ 24 653]]
              precision    recall  f1-score   support

        fake       0.96      0.94      0.95       607
        real       0.94      0.96      0.95       677

    accuracy                           0.95      1284
   macro avg       0.95      0.95      0.95      1284
weighted avg       0.95      0.95      0.95      1284

0.9509345794392523


In [72]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()
classifier.fit(tfidf_train, y_train)


LogisticRegression()

In [73]:
y_pred5 = classifier.predict(tfidf_test)

In [74]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred5))
print(classification_report(y_test,y_pred5))
print(accuracy_score(y_test, y_pred5))

[[568  39]
 [ 43 634]]
              precision    recall  f1-score   support

        fake       0.93      0.94      0.93       607
        real       0.94      0.94      0.94       677

    accuracy                           0.94      1284
   macro avg       0.94      0.94      0.94      1284
weighted avg       0.94      0.94      0.94      1284

0.9361370716510904


In [81]:
# Voting Classifier
print("Voting Classifier")
from sklearn.naive_bayes import MultinomialNB

#lr = LogisticRegression()
#dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
#rp = BaggingClassifier()
passive = PassiveAggressiveClassifier()
clf = MultinomialNB()
#SVM = svm.SVC()
#clf2 = LogisticRegression()


#svm = SVC(kernel='poly', degree=2)
evc = VotingClassifier(estimators=[
     ('rf', rf),('passive',passive),('clf',clf)], voting='hard')
evc.fit(tfidf_train, y_train)
print(evc.score(tfidf_test, y_test))
print(classification_report(y_test, y_pred, digits=6))





Voting Classifier
0.9478193146417445


NameError: name 'y_pred' is not defined